export interface ILatestData {
  id: string;
  timestamp: string;
  latest: string;
  elapsed: string;
  localName: string;
  temperature: number;
  humidity: number;
  pressure: number;
  light_A: number;
  sol: number;
  acc_x: number;
  acc_y: number;
  acc_z: number;
  iaq: number;
  gyro_x: number;
  gyro_y: number;
  gyro_z: number;
  accuracy: number;
  gaz: number;
  co2: number;
  SeuilHumidity_min: number;
  SeuilHumidity_max: number;
  SeuilTemp_min: number;
  SeuilTemp_max: number;
  SeuilLum_min: number;
  SeuilLum_max: number;
  SeuilPression_min: number;
  SeuilPression_max: number;
  SeuilCo2_min: number;
  SeuilCo2_max: number;
  MeanTemp: number;
  MeanHumidity: number;
  MeanLum: number;
  MeanPress: number;
  MeanCo2: number;
  S1: number;
  S2: number;
  S3: number;
  S4: number;
  S5: number;
  S6: number;
  S7: number;
  S8: number;
  S9: number;
  S10: number;
  S11: number;
  S12: number;
  S13: number;
  S14: number;
  S15: number;
  S16: number;
  PolStartTime: string | null;
  PolEndTime: string | null;
  Periode: string | null;
  MomentFloraison: boolean;
  a1: number;
  a2: number;
  a3: number;
  a4: number;
  a5: number;
  a6: number;
  a7: number;
  a8: number;
  a9: number;
  a10: number;
  pollinationStartTime: string | null;
  pollinationEndTime: string | null;
  PeriodePol: string | null;
  ManuelAutoS1: number;
  ManuelAutoS2: number;
  ManuelAutoS3: number;
  ManuelAutoS4: number;
  ManuelAutoS5: number;
  ManuelAutoS6: number;
  ManuelAutoS7: number;
  ManuelAutoS8: number;
  ManuelAutoS9: number;
  ManuelAutoS10: number;
  ManuelAutoS11: number;
  ManuelAutoS12: number;
  ManuelAutoS13: number;
  ManuelAutoS14: number;
  ManuelAutoS15: number;
  ManuelAutoS16: number;
  MonitorTime: string | null;
  cultureInfosId: string | null;
  sensorDataForMinuteId: string | null;
  sensorDataForHourId: string | null;
  sensorDataForDayId: string | null;
}


export interface ILatestDataState  {
  data: ILatestData | null;
  loading: boolean;
  error: string | null;
}

